---
title: "2017 NBA  Team Stats"
author: "Jay Fisher"
date: "November 8, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# load packages
library(rvest)
library(stringr)
library(dplyr)
library(readr)
library(ggplot2)

# Read in standings from Basketball Reference
url <- "http://www.basketball-reference.com/leagues/NBA_2017_standings.html" 

url <- read_html(url)

# Clean Eastern Conference
# Get the standings table
east <- html_table(html_nodes(url, "table"))[[1]]

# lowercase column names
names(east) <- tolower(names(east))

# remove division rows
# east <- east[-grep("Division", east$`eastern conference`),]

# convert tm_pts and op_pts to integers
east$tm_pts <- as.numeric(east$`ps/g`)
east$op_pts <- as.numeric(east$`pa/g`)

# remove pts columns
east$`ps/g` <- NULL
east$`pa/g` <- NULL

# rename eastern conference to team
east <- rename(east, "team" = `eastern conference`)

# add conference column; add "east" to it
east$conf <- "East"

# remove asterisk from team column
east$team <- str_replace_all(east$team, "\\*", "")

# conference rank from team column to separate column
east$conf_rank <- str_extract(east$team, "[[:space:]]\\([[:alnum:]]{1,}\\)[[:space:]]")
east$conf_rank <- str_replace_all(east$conf_rank, "[[:punct:]]|[[:space:]]", "")
east$conf_rank <- as.integer(east$conf_rank)

# remove conference rank from team column
east$team <- str_replace_all(east$team, "[[:punct:]][[:digit:]]{1,2}[[:punct:]]", "") %>% str_trim

# calculate point differential
east <- mutate(east, pt_diff = tm_pts - op_pts)

# Clean Western Conference
# Get the standings table
west <- html_table(html_nodes(url, "table"))[[2]]

# lowercase column names
names(west) <- tolower(names(west))

# convert tm_pts and op_pts to integers
west$tm_pts <- as.numeric(west$`ps/g`)
west$op_pts <- as.numeric(west$`pa/g`)

# remove pts columns
west$`ps/g` <- NULL
west$`pa/g` <- NULL

# rename western conference to team
west <- rename(west, "team" = `western conference`)

# add conference column; add "west" to it
west$conf <- "West"

# remove asterisk from team column
west$team <- str_replace_all(west$team, "\\*", "")

# conference rank from team column to separate column
west$conf_rank <- str_extract(west$team, "[[:space:]]\\([[:alnum:]]{1,}\\)[[:space:]]")
west$conf_rank <- str_replace_all(west$conf_rank, "[[:punct:]]|[[:space:]]", "")
west$conf_rank <- as.integer(west$conf_rank)

# remove conference rank from team column
west$team <- str_replace_all(west$team, "[[:punct:]][[:digit:]]{1,2}[[:punct:]]", "") %>% str_trim

# calculate point differential
west <- mutate(west, pt_diff = tm_pts - op_pts)

# Bind east and west conference; round pt_diff for matching
standings <- rbind(east, west) %>% arrange(conf, conf_rank) %>% select(-gb, -srs)

# Add rank
standings <- mutate(standings, off_rank = min_rank(desc(tm_pts)), def_rank = min_rank((op_pts)), pt_diff_rank = min_rank(desc(pt_diff)))

```

Here are different ways to show what the 2016-17 NBA season looks right now.

First up, the Eastern Conference:

```{r, echo=FALSE}
filter(standings, conf == "East") %>% 
  ggplot(aes(x = conf_rank, y = pt_diff)) + 
  geom_point(aes(color = conf), size = 5, alpha = 0.5) +
  xlim(1,15) +
  geom_vline(xintercept = 8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Conference Rank", y = "Point Differential", title = "Eastern Conference: Point Differential by Conference Rank" ) +
  theme_bw()
```

The Western Conference:

```{r, echo=FALSE}
filter(standings, conf == "West") %>% 
  ggplot(aes(x = conf_rank, y = pt_diff)) + 
  geom_point(aes(color = team), size = 5, alpha = 0.5) +
  xlim(1,15) +
  geom_vline(xintercept = 8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(x = "Conference Rank", y = "Point Differential", title = "Western Conference: Point Differential by Conference Rank" ) +
  theme_bw()
```


Here are the Eastern Conference standings:
```{r}
library(formattable)

# formattable(east,
#             list(
#                conf_rank = color_tile("white", "orange"))
#             )

formattable(east,
            list(
               team = formatter("span", 
          style = x ~ style(color = ifelse(east$conf_rank <= 8, "green", "red"))))
)
```

```{r}

east$pt_diff <- round(east$pt_diff, 1)
datatable(data = east, class = 'cell-border stripe', 
          options = list(pageLength = 15))
```


Using scatterD3
```{r, echo=FALSE}
library(scatterD3)
scatterD3(data = standings, x = conf_rank, y = pt_diff,
          lines = data.frame(slope = c(0, Inf), 
                             intercept = c(0,8),
                             stroke = "#000",
                             stroke_width = 1,
                             stroke_dasharray = 5),
          col_var = team,
          legend_width = 0,
          point_size = 200, point_opacity = 0.5,
          hover_size = 4, hover_opacity = 1,
          xlim = c(0,16))

```

